name: Envoyer un fichier créé par GitHub Actions par e-mail

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code source
        uses: actions/checkout@v2

      - name: Créer le fichier
        run: echo "Contenu du fichier" > fichier.txt

      - name: Upload du fichier
        uses: actions/upload-artifact@v2
        with:
          name: fichier
          path: fichier.txt

      - name: Envoyer le fichier par e-mail
        uses: dawidd6/action-send-mail@v3
        with:
            server_address: smtp.gmail.com
            server_port: 587
            username: ${{ secrets.MAIL_ADDRESS}}
            password: ${{ secrets.MAIL_PASSWORD}}
            subject: "Nouveau fichier"
            body: "Un nouveau fichier a été créé et ajouté en pièce jointe."
            from: ${{ secrets.MAIL_ADDRESS }}
            to: "mignzii99@gmail.com"
            attachments: ${{ runner.workspace }}/fichier.txt
